Proyecto 207910029/Web/Controllers/TipoActivoController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Security;

namespace Web.Controllers
{

    [CustomAuthorize((int)Roles.Administrador, (int)Roles.Procesos)]
    public class TipoActivoController : Controller
    {
        
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult List()
        {
            IEnumerable<TipoActivo> lista = null;
            try
            {
                Log.Info("Visita");


                IServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();
                lista = _ServiceTipoActivo.GetTipoActivo();
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());

                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                // Redireccion a la captura del Error

                return RedirectToAction("Default", "Error");
            }

            return View(lista);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        // [CustomAuthorize((int)Roles.Administrador)]
        public ActionResult Save(TipoActivo tipoActivo)
        {
            string errores = "";
            try
            {
                // Es valido
                if (ModelState.IsValid)
                {
                    ServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();
                    _ServiceTipoActivo.Save(tipoActivo);
                    TempData["Action"] = "S";
                }
                else
                {
                    // Valida Errores si Javascript está deshabilitado
                    Util.ValidateErrors(this);

                    TempData["Message"] = "Error al procesar los datos! " + errores;
                    TempData.Keep();

                    return View("Create", tipoActivo);
                }

                // redirigir
                return RedirectToAction("List");

            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                ViewBag.Message = TempData["Message"];
                @TempData["Action"] = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("List");
            }
        }

        // GET: Bodega/Details/5      

        public ActionResult Details(int id)
        {
            ServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();
            TipoActivo tipoActivo = null;

            try
            {
                

                tipoActivo = _ServiceTipoActivo.GetTipoActivoByID(id);

                return View(tipoActivo);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                @TempData["Action"] = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("List");
            }
        }

        // GET: Bodega/Edit/5

        public ActionResult Edit(int id)
        {
            ServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();
            TipoActivo tipoActivo = null;
            try
            {


                tipoActivo = _ServiceTipoActivo.GetTipoActivoByID(id);


                // Response.StatusCode = 500;
                return View(tipoActivo);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                @TempData["Action"] = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("List");
            }
        }


        // GET: Bodega/Delete/5

        public ActionResult Delete(int id)
        {
            try
            {
                


                ServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();
                TipoActivo tipoActivo = _ServiceTipoActivo.GetTipoActivoByID(id);

                return View(tipoActivo);
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                @TempData["Action"] = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("List");
            }
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]

        public ActionResult DeleteConfirmed(int id)
        {
            ServiceTipoActivo _ServiceTipoActivo = new ServiceTipoActivo();

            try
            {

                


                _ServiceTipoActivo.DeleteTipoActivo(id);
                TempData["Action"] = "D";
                return RedirectToAction("List");
            }
            catch (Exception ex)
            {
                // Salvar el error en un archivo 
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                TempData.Keep();
                @TempData["Action"] = "E";
                // Redireccion a la captura del Error
                return RedirectToAction("List");
            }
        }
    }
}

Proyecto 207910029/Web/Views/TipoActivo/Create.cshtml
@model Infraestructure.Models.TipoActivo

@{
    ViewBag.Title = "Crear Tipo Activo";
}

<h2>Crear</h2>

@if (TempData["Message"] != null)
{
    string mensaje = @"<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'>
<span aria-hidden='true'>&times;</span> </button>
<strong>Error!</strong> " + TempData["Message"] + " </div>";

@Html.Raw(mensaje);
}

@using (Html.BeginForm("Save", "TipoActivo", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tipo Activo</h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VidaUtil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VidaUtil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VidaUtil, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Crear" class="btn btn-primary btn-block pull-left" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Volver a la lista", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Proyecto 207910029/Web/Views/TipoActivo/Delete.cshtml
@model Infraestructure.Models.TipoActivo

@{
    ViewBag.Title = "Borrar Tipo Marca";
}

<h2>Borrar</h2>

<h3>Seguro que deseas borrar?</h3>

@if (TempData["Message"] != null)
{
    string mensaje = @"<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'>
<span aria-hidden='true'>&times;</span> </button>
<strong>Error!</strong> " + TempData["Message"] + " </div>";

@Html.Raw(mensaje);
}
<div>

    <hr />
    @using (Html.BeginForm("DeleteConfirmed", "TipoActivo", new { id = Model.Id }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Id)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descripcion)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.VidaUtil)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.VidaUtil)
            </dd>
        </dl>




        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> |
            @Html.ActionLink("Volver a la Lista", "List")
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

Proyecto 207910029/Web/Views/TipoActivo/Details.cshtml
@model Infraestructure.Models.TipoActivo

@{
    ViewBag.Title = "Detalles Tipo Marca";
}

<h2>Detalles</h2>

<div>
    <h4>Tipo Activo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VidaUtil)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VidaUtil)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Volver a la lista", "List")
</p>

Proyecto 207910029/Web/Views/TipoActivo/Edit.cshtml
@model Infraestructure.Models.TipoActivo

@{
    ViewBag.Title = "Editar Tipo Activo";
}

<h2>Editar</h2>

@if (TempData["Message"] != null)
{
    string mensaje = @"<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'>
<span aria-hidden='true'>&times;</span> </button>
<strong>Error!</strong> " + TempData["Message"] + " </div>";

@Html.Raw(mensaje);
}

@using (Html.BeginForm("Save", "TipoActivo", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Tipo Activo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.VidaUtil, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.VidaUtil, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VidaUtil, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Actualizar" class="btn btn-primary btn-block pull-left" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver a la lista", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

Proyecto 207910029/Web/Views/TipoActivo/List.cshtml
@model IEnumerable<Infraestructure.Models.TipoActivo>

@{
    ViewBag.Title = "Lista Tipo Activo";
}

<h2>Tipo Activo</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create", null, htmlAttributes: new { @class = "btn btn-success glyphicon-plus" })
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VidaUtil)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Descripcion)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.VidaUtil)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-primary" })
        @Html.ActionLink("Detalles", "Details", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-warning" })
        @Html.ActionLink("Borrar", "Delete", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-danger" })
    </td>
</tr>
    }

</table>


@section Scripts {
    @Scripts.Render("~/bundles/toastjs")
    @Scripts.Render("~/bundles/jqueryui")




    <script>

        $(document).ready(function () {
             console.log("Entro a JQuery")

            toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": false,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "400",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "5000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }

                // Recibe los parámetros del Controller
                var option = '@TempData["Action"]'
                var message = '@TempData["Message"]'


                if (option == 'S') {
                    toastr.success("El registro fue salvado correctamente");
                }


                 if (option == 'D') {
                    toastr.success("El registro fue borrado correctamente");
                }


                 if (option == 'U') {
                    toastr.success("El registro fue actualizado correctamente");
                }

                if (option == 'E') {
                    toastr.warning("Se ha producido un error :"+message);
            }


            // Cambiar el color del fondo del Grid.
            //$(".table tbody tr:even").css("background-color", "#ddd");
        });



    </script>

 }